name: Detect Secrets

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  detect-secrets:
    name: Yelp detect-secrets
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar detect-secrets
        run: pip install detect-secrets==1.5.0

      - name: Buscar secretos
        continue-on-error: true
        run: git ls-files -z | xargs -0 detect-secrets-hook
